feat: создать filmorate
KhorkovRoman/java-filmorate pull request #1
Opened 2022-06-09 18:22 UTC by KhorkovRoman

2022-06-10 14:10 UTC, Fleaman777 requested changes

2022-06-10 14:10 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +	FilmController filmController = new FilmController();
инициализацию полей можно вынести в метод с аннотацией @BeforeEach 
так будет более правильный подход .

На данный момент он преимущества не дает, но в будущем, будет проще управлять объектами для теста

2022-06-10 14:10 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public void getValidation(User user) {
возможно в нашем случае, и на данный момент, создание отдельного класса в котором будут лежать валидационные методы избыточно,

но более правильный подход тогда, когда контроллер только принимает запросы и отдает респонсы, а всю остальную логику выполняют другие классы(сервисы)

это не считается ошибкой,
выносить этот метод в отдельный класс или нет остается за тобой :)

аналагично и в фльм контроллере

2022-06-10 14:10 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +				"jdklgjalksjflksdfjaldskfj;alsdfj;alksdjf;alsdjf;alksdjf;alksdjflaksdjfkdjfakdljfkldasjf");
такую длинную строку можно было бы вынести в константу, что бы тест проще воспринимался, и в нем содержалась только та информация, которая имеет отношение к выполнению теста (что именно написано в длинном дескрипшене не важно, важно что он достаточно длинный что бы проверить, как работает проверка)

2022-06-10 14:10 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	}
В enterprise приложениях на java, особенно написанных на Spring, в ....ControllerTest обычно тестируется api - на контроллер приходят определенные запросы(это делается специальной сущностью, а не просто вызывается эндпоинт метод), приложение полностью все отрабатывает, и затем отвечает определенным кодом и response body, которые и проверяются - такие тесты называются интеграционными.
Валидацию хорошо тестировать в обычных юнит тестах. Как раз, это будет проще сделать, если ее вынести в отдельный класс в отдельной директории.

этот комментарий тоже больше для информации,
если вдруг решишь часть валидации вынести в отдельный класс, можешь частично реализовать этот подход

2022-06-10 14:10 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +public class ValidationException extends RuntimeException {
ValidationException можно наследовать от ResponseStatusException,
и потом использовать конструктор:

public ValidationException(HttpStatus status, String massage) {
super(status, massage);
}

где status какой-нибудь соответсвующий ошибке Http статус

2022-06-10 17:57 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public void getValidation(User user) {
я пока оставлю валидацию здесь в методе, но запомню и в следующем задании уже учту это

2022-06-10 17:58 UTC, KhorkovRoman commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	}
пока оставлю валидацию в методе

2022-06-11 18:22 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +public class ValidationException extends RuntimeException {
поменял статусы

2022-06-11 18:22 UTC, KhorkovRoman commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +				"jdklgjalksjflksdfjaldskfj;alsdfj;alksdjf;alsdjf;alksdjf;alksdjflaksdjfkdjfakdljfkldasjf");
вынес в константу

2022-06-11 18:25 UTC, KhorkovRoman commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +	FilmController filmController = new FilmController();
вынес в метод с аннотацией @BeforeEach

2022-06-11 18:27 UTC, KhorkovRoman commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +	FilmController filmController = new FilmController();
вынес в метод с аннотацией "@BeforeEach"

2022-06-11 18:28 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        getValidation(film);
исправил

2022-06-11 18:28 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +//    }
удалил

2022-06-11 18:29 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public void getValidation(Film film) {
исправил

2022-06-11 18:29 UTC, KhorkovRoman commented on .idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
в .gitignore исключения настроены

2022-06-11 19:56 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    int duration;
исправил

2022-06-11 19:57 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    LocalDate birthday;
исправил

2022-06-11 19:57 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +public class UserController {
тут не понял, что нужно сделать

2022-06-11 19:58 UTC, KhorkovRoman commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +
исправил

2022-06-11 20:44 UTC, Fleaman777 requested changes

2022-06-11 20:44 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    int filmId = 0;
это поле тоже можно сделать private, т.к. извне оно никак не будет использоваться, только внутри этого класса

2022-06-11 20:44 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    int userId = 0;
здесь тоже private

2022-06-11 20:44 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +public class UserController {
имел ввиду, что все замечания, которые указал в FilmController'е здесь тоже нужно исправить

2022-06-11 20:44 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +	Film film;
тоже поля можно сделать private. возможно в тестах принцип инкапсуляции не так критичен, но все равно лучше придерживатся одного стиля

2022-06-11 20:44 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
Название не совсем соответствуюет тестам внутри, UserControllerTest подошло бы больше

2022-06-11 20:55 UTC, KhorkovRoman commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
исправил

2022-06-11 20:55 UTC, KhorkovRoman commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +	Film film;
исправил

2022-06-11 20:55 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    int userId = 0;
исправил

2022-06-11 20:55 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    int filmId = 0;
исправил

2022-06-12 16:48 UTC, merged