feat: сделать добавление в друзья и лайки фильмов
KhorkovRoman/java-filmorate pull request #2
Opened 2022-06-16 20:22 UTC by KhorkovRoman

2022-06-17 20:08 UTC, Fleaman777 requested changes

2022-06-17 20:40 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/ValidationFilm.java
> +public class ValidationFilm {
Спринг бин и заавтовайрить я не знаю, что это

2022-06-18 16:06 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        return filmService.getFilmStorage().createFilm(film);
сделал

2022-06-18 16:08 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
>      public Film put(@Valid @RequestBody Film film) {
сделал

2022-06-18 16:09 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Integer> likes = new HashSet<>();
ок

2022-06-18 16:14 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/ValidationFilm.java
> +public class ValidationFilm {
сделал

2022-06-18 16:30 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                Film film = filmStorage.getFilms().get(filmId);
сделал

2022-06-18 17:06 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    ComparatorFilmsLikes comparatorFilmsLikes = new ComparatorFilmsLikes();
сделал

2022-06-18 18:35 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    }
сделал в FilmService и UserService, действительно читается лучше

2022-06-19 15:34 UTC, Fleaman777 requested changes

2022-06-19 15:34 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .collect(Collectors.toList());
здорово, это совершенно другой уровнеь :)

2022-06-19 15:34 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    ValidationFilm validationFilm;
поле должно быть private

2022-06-19 15:34 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            Film film = filmStorage.getFilmById(filmId);
можно сразу вызывать getFilmById(id), 
в случае, если в мапе не будет фильма с запрошенным айдишником, метод просто вернет null, потом сделать проверку если null, то выбросим исключение, если все в пордяке, вернем фильм

таким образом,  не нужно будет делать проверку filmStorage.getFilms().containsKey(filmId)

применимо ко всем схожим местам

2022-06-19 15:34 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        }
что бы код чуть легче воспринимался, эти 2 ифа можно разделить, сделать их друг за другом, т.е. сначал например сделать так

if (userStorage.getUserById() == null) {
throw......
}
if (filmStorage.....) {
throw....
}
....

2022-06-19 15:34 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                return matches;
здесь тоже можешь попробовать переделать foreach на стримы, 
если получится, должно быть компактно и красиво :)

2022-06-19 16:44 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    ValidationFilm validationFilm;
сделал

2022-06-19 17:27 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                return matches;
я уже реализовал, вроде красиво выглядит :)         

List<User> matches = userFriendList.stream()
                .filter(otherUserFriendList::contains)
                .collect(Collectors.toList());

2022-06-19 17:40 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            Film film = filmStorage.getFilmById(filmId);
сделал.

2022-06-19 17:44 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        }
оставил одну проверку if (userStorage.getUsers().containsKey(userId)) 
userId использвуется в filmLikes.add(userId); , тут не знаю, как проверить на null, 
считаю, что нужно оставить проверку, есть ли пользователь в базе

2022-06-19 17:44 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .collect(Collectors.toList());
сам удивлен

2022-06-20 17:40 UTC, merged