feat: добавить базу данных
KhorkovRoman/java-filmorate pull request #4
Opened 2022-07-15 19:49 UTC by KhorkovRoman

2022-07-16 11:49 UTC, KhorkovRoman commented
в файл readme.md добавляю картинку схему базы данных, показывает конфликт, удаляю - конфликта нет, не понимаю, как правильно добавить картинку, чтобы не было конфликта

2022-07-16 15:38 UTC, KhorkovRoman commented
разобрался , как добавить картинку

2022-07-17 10:45 UTC, Fleaman777 requested changes

2022-07-17 10:45 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDBStorage.java
> +                , film.getMpa().getId()
film.getMpa().getId() можно было бы вынести в локальную переменную, что бы не дублировать ее получение

2022-07-17 10:45 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDBStorage.java
> +        final String sqlQuery = "DELETE FROM FILMS WHERE FILM_ID = ?";
для чуть более простого воспрятия sql запросов, ключевые слова наподобие DELETE, FROM и др. можно делать в верхнем регистре, а названи таблиц, столбцов в нижнем

2022-07-17 10:45 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/dao/FriendDBStorage.java
> +    static FriendStatus makeStatus(ResultSet rs, int rowNum) throws SQLException {
метод можно не сделать обычным , не статичным

2022-07-17 10:45 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/dao/FriendDBStorage.java
> +                " WHERE FU.USER_ID = ? AND FO.USER_ID = ?";
отличный, грамотный join

2022-07-17 10:45 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/FilmoRateApplicationTests.java
> +        userStorage.createUser(user);
создание юзера тоже можно было бы вынести в метод initFields

2022-07-17 10:45 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/FilmoRateApplicationTests.java
> +    }
тесты неплохие, 
но лучше их перенести в соответсвующие тестовые классы дб стореджей, 
так будет соблюден принцип разделения ответсвенности, 
+ будет проще ориентироваться в тестах

2022-07-17 10:45 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/FilmoRateApplicationTests.java
> +
так же, согласно заданию,
необходимо покрыть все публичные методы всех стореджей

2022-07-17 13:17 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDBStorage.java
> +                , film.getMpa().getId()
в каждом методе я получаю film и уже от него получаю film.getMpa().getId(), я добавил новую переменную в каждом методе, где их по две, где по одному я не стал добавлять

2022-07-17 13:17 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDBStorage.java
> +        final String sqlQuery = "DELETE FROM FILMS WHERE FILM_ID = ?";
сделал

2022-07-17 13:20 UTC, KhorkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/dao/FriendDBStorage.java
> +    static FriendStatus makeStatus(ResultSet rs, int rowNum) throws SQLException {
если убираю static , то в методе getStatusFriendship() не отпределяется sql, я ведь делал так же как и в makeUser(), там также стоит static

2022-07-17 13:22 UTC, KhorkovRoman commented on src/test/java/ru/yandex/practicum/filmorate/FilmoRateApplicationTests.java
> +        userStorage.createUser(user);
сделал

2022-07-18 07:10 UTC, KhorkovRoman commented on src/test/java/ru/yandex/practicum/filmorate/FilmoRateApplicationTests.java
> +
тесты дописал

2022-07-18 07:10 UTC, KhorkovRoman commented on src/test/java/ru/yandex/practicum/filmorate/FilmoRateApplicationTests.java
> +    }
тесты разделил по классам

2022-07-18 18:04 UTC, Fleaman777 requested changes

2022-07-18 18:04 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/FilmDBStorageTests.java
> +        assertEquals(1, films.size());
можно сразу сделать assertEquals(1, filmStorage.getAllFilms().size()), без создания отдельной переменной

2022-07-18 18:14 UTC, merged